-- Datos que tenía el sitio antes de pasar a la base de datos.

insert into public.categorias (id, nombre, corto, descripcion, foto, orden) values
  ('rosas', 'Rosas de listón satinado', 'Rosas', 'Rosas eternas con el color que elijas.', '/src/assets/productos/ramo-12-rosas-clasicas-1.jpg', 1),
  ('girasoles', 'Girasoles de listón satinado', 'Girasoles', 'Girasoles que no se marchitan.', '/src/assets/productos/ramo-chico-girasoles-1.jpg', 2),
  ('hot-wheels', 'Ramos de Hot Wheels y flores de listón', 'Hot Wheels', 'Carritos y color de rosas a elegir.', '/src/assets/productos/carrito-3-1.jpg', 3);

insert into public.productos (id, nombre, categoria, resumen, precio, descripcion, fotos, opciones, disponible, destacado, orden) values
  ('carrito-1', 'Carrito 1', 'hot-wheels', 'Ramo 1 carrito 1 rosa', 90, 'Ramo con 1 carrito Hot Wheels y 1 rosa eterna de listón satinado. Los modelos de carritos dependen de las existencias: dinos qué te gusta y te confirmamos por WhatsApp.', '[{"src":"/src/assets/productos/carrito-1-1.jpg","alt":"Ramo con un carrito Hot Wheels verde y una rosa azul en papel negro"}]'::jsonb, '[{"nombre":"Color de la rosa","ejemplo":"azul, roja, negra..."},{"nombre":"Carrito que te gusta","ejemplo":"deportivo, clásico, camioneta..."}]'::jsonb, true, false, 1),
  ('carrito-2', 'Carrito 2', 'hot-wheels', 'Ramo 3 carritos 3 rosas', 290, 'Ramo con 3 carritos Hot Wheels y 3 rosas eternas de listón satinado. Los modelos de carritos dependen de las existencias: dinos qué te gusta y te confirmamos por WhatsApp.', '[{"src":"/src/assets/productos/carrito-2-1.jpg","alt":"Ramo con 3 carritos Hot Wheels y rosas rojas en papel negro con moño rojo"}]'::jsonb, '[{"nombre":"Color de rosas","ejemplo":"rojas, azules, negras..."},{"nombre":"Carritos que te gustan","ejemplo":"deportivos, clásicos, camionetas..."}]'::jsonb, true, true, 2),
  ('carrito-3', 'Carrito 3', 'hot-wheels', 'Ramo 3 carritos 5 rosas', 380, 'Ramo con 3 carritos Hot Wheels y 5 rosas eternas de listón satinado. Los modelos de carritos dependen de las existencias: dinos qué te gusta y te confirmamos por WhatsApp.', '[{"src":"/src/assets/productos/carrito-3-1.jpg","alt":"Ramo con 3 carritos Hot Wheels y rosas azules en papel negro con moño azul"}]'::jsonb, '[{"nombre":"Color de rosas","ejemplo":"azules, rojas, negras..."},{"nombre":"Carritos que te gustan","ejemplo":"deportivos, clásicos, camionetas..."}]'::jsonb, true, false, 3),
  ('carrito-duo', 'Carrito duo', 'hot-wheels', 'Ramo 2 carritos 2 rosas', 220, 'Ramo con 2 carritos Hot Wheels y 2 rosas eternas de listón satinado. Los modelos de carritos dependen de las existencias: dinos qué te gusta y te confirmamos por WhatsApp.', '[{"src":"/src/assets/productos/carrito-duo-1.jpg","alt":"Ramo con 2 carritos Hot Wheels y rosas azules en papel negro con moño azul"}]'::jsonb, '[{"nombre":"Color de rosas","ejemplo":"azules, rojas, negras..."},{"nombre":"Carritos que te gustan","ejemplo":"deportivos, clásicos, camionetas..."}]'::jsonb, true, false, 4),
  ('mix-girasol-y-rosas', 'Mix Girasol y Rosas', 'girasoles', '', 290, 'Ramo de listón satinado con girasol al centro y rosas del color que elijas.', '[{"src":"/src/assets/productos/mix-girasol-y-rosas-1.jpg","alt":"Ramo con un girasol al centro rodeado de rosas rojas, en papel negro con moño rojo"}]'::jsonb, '[{"nombre":"Color de rosas","ejemplo":"rojo, rosa, azul..."}]'::jsonb, true, true, 3),
  ('ramo-12-rosas-clasicas', 'Ramo 12 rosas clásicas', 'rosas', '12 rosas', 370, 'Ramo de 12 rosas eternas de listón satinado, del color que elijas.', '[{"src":"/src/assets/productos/ramo-12-rosas-clasicas-1.jpg","alt":"Ramo de 12 rosas azul cielo envuelto en papel azul claro con moño crema"}]'::jsonb, '[{"nombre":"Color de rosas","ejemplo":"azul cielo, rojo, rosa..."}]'::jsonb, true, false, 3),
  ('ramo-chico-de-rosas', 'Ramo chico de rosas', 'rosas', 'Rosas clásicas', 220, 'Ramo de 7 rosas eternas de color a elección envueltas en papel coreano con un moño decorativo.', '[{"src":"/src/assets/productos/ramo-chico-de-rosas-1.jpg","alt":"Ramo de 7 rosas color durazno envuelto en papel blanco con vetas doradas y moño crema"}]'::jsonb, '[{"nombre":"Color de rosas","ejemplo":"durazno, rojo, azul..."}]'::jsonb, true, true, 2),
  ('ramo-chico-girasoles', 'Ramo chico girasoles', 'girasoles', '', 250, 'Ramo de girasoles de listón satinado, hecho a mano.', '[{"src":"/src/assets/productos/ramo-chico-girasoles-1.jpg","alt":"Ramo de girasoles de listón envuelto en papel rosa y dorado"}]'::jsonb, '[]'::jsonb, true, false, 2),
  ('ramo-de-rosas-mediano', 'Ramo de rosas mediano', 'rosas', '24 rosas', 680, 'Ramo de 24 rosas eternas de listón satinado. Puedes combinar colores.', '[{"src":"/src/assets/productos/ramo-de-rosas-mediano-1.jpg","alt":"Ramo de 24 rosas vino y blancas con mariposas doradas, envuelto en papel dorado"}]'::jsonb, '[{"nombre":"Color de rosas","ejemplo":"vino y blanco, rojo..."}]'::jsonb, true, true, 4),
  ('rosa-eterna', 'Rosa eterna', 'rosas', 'Rosas clásicas', 50, 'Rosa eterna hecha a mano con listón satinado. Dinos el color que prefieres y te confirmamos disponibilidad.', '[{"src":"/src/assets/productos/rosa-eterna-1.jpg","alt":"Rosa roja de listón satinado envuelta en papel negro con moño rojo"}]'::jsonb, '[{"nombre":"Color de la rosa","ejemplo":"roja, rosa, azul..."}]'::jsonb, true, false, 1),
  ('unico-girasol', 'Único Girasol', 'girasoles', 'Girasol clásico movible', 90, 'Girasol clásico de listón satinado, hecho a mano.', '[{"src":"/src/assets/productos/unico-girasol-1.jpg","alt":"Girasol amarillo de listón satinado con tallo verde"}]'::jsonb, '[]'::jsonb, true, false, 1);
